---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
  - name: Add key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com
  - name: Add repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
  - name: Install mongodb
    apt:
      name: mongodb-org
      state: present
      force: yes
  - name: Start mongodb
    systemd:
      name: mongod
      enabled: yes
